[project]
name = "smevals"
version = "0.2.0"
description = "A framework for running evals against small (and large) models"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Simon Willison" }
]
requires-python = ">=3.10"
dependencies = [
    "click>=8.4.2",
    "pyyaml>=6.0.3",
]

[project.scripts]
smevals = "smevals.cli:cli"

[build-system]
requires = ["uv_build>=0.11.0,<0.12.0"]
build-backend = "uv_build"
